# Make sure this is set to "kotlinforforge"
modLoader = "kotlinforforge"
# Make sure this is set to the appropriate version range
loaderVersion = "[2,)" # Require at least 1.14.x
# License is REQUIRED after 1.16
license = "LGPL-2.1-or-later"

[[mods]]
modId = "example_mod"
version = "${file.jarVersion}"
displayName = "ExampleMod"
authors = "Author"
description = '''
    Example mod that uses Kotlin for Forge.
    '''
[[dependencies.example_mod]]
modId = "forge"
mandatory = true
versionRange = "[37,)"
ordering = "NONE"
side = "BOTH"
[[dependencies.example_mod]]
modId = "minecraft"
mandatory = true
versionRange = "[1.17.1]"
ordering = "NONE"
side = "BOTH"
